# permissions for end users to view attendancebooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: attendancebook-viewer-role
rules:
- apiGroups:
  - office.a2ush.dev
  resources:
  - attendancebooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - office.a2ush.dev
  resources:
  - attendancebooks/status
  verbs:
  - get
